# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2
language: rust
rust:
  - stable
  - beta
  - nightly
sudo: required
env: TARGET=x86_64-unknown-linux-gnu

# TODO Rust builds on stable by default, this can be
# overridden on a case by case basis down below.
matrix:
  allow_failures:
    - rust: nightly
    - name: clippy
  fast_finish: true


before_install:
  - set -e
  - rustup self update

# install:
#   - cargo install cargo-update || echo "cargo-update already installed"
#   - cargo install-update -a # update outdated cached binaries
#   - cargo install cross || echo "cross already installed"

  #TODO: remove -A clippy::new_ret_no_self when new version of clippy gets released!
script:
  - cross check --verbose
  - cross test --all-features --release --verbose

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo
  - | 
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
      cargo install cargo-tarpaulin -f
    fi

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    # Uncomment the following line for coveralls.io
    # cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    # Uncomment the following two lines create and upload a report for codecov.io
    cargo tarpaulin --all-features --out Xml
    bash <(curl -s https://codecov.io/bash) -t "$CODECOV_TOKEN"
  fi


branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
