[package]
name = "eink_waveshare_rs"
version = "0.1.0"
authors = ["Christoph Groß <christoph.gross@student.uni-tuebingen.de>"]


[features]
default = ["epd1in54", "epd2in9", "epd4in2"]

epd1in54 = []
epd2in9 = []
epd4in2 = []
# Activates the fast LUT for EPD4in2
epd4in2_fast_update = []

[dependencies]


[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.1"
