[package]
name = "eink_waveshare_rs"
version = "0.1.0"
authors = ["Christoph Groß <christoph.gross@student.uni-tuebingen.de>"]

[dependencies]


[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.1"
